# Setup
title:               "sinefuse's corner"
tagline:             ""
description:         "This is sinefuse's personal website."
url:                 https://sinefuse.moe
baseurl:             ''
permalink:           pretty

# About/contact
author:
  name:              sinefuse
  url:               https://sinefuse.moe

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             2.0.0